### ISSUE TITLE
#include <opus_multistream.h> incorrect

### ISSUE THREAD

**Issue by krcroft** [xiph/opusfile#10]
opusfile.h contains:

`# include <opus_multistream.h>`

Which would be fine if `/usr/include/ opus_multistream.h` was available in a base $INCLUDE directory, but opus_multistream.h only exists inside 'opus/'.  

So it should be:

`# include "opus_multistream.h"`

Which matches other opus headers, or

`# include <opus/opus_multistream.h>`

**Comment by tterribe** [comment]
This is working as intended. You are supposed to add the opus include directory to your search path (and pkg-config --cflags opus will do this in the default autotools build system). This is the way that libopus is designed, and not an issue with opusfile.

**Comment by krcroft** [comment]
I agree that opusfile.h _will_ find <opus_multistream.h>  if you explicitly pass in the _opus_ directory itself, such as `-I/usr/include/opus` or `-I/usr/local/include/opus`  to the compiler or via configure/pkg-config. 

However, that's not how the opus parent library works. See how opus.h does it here: headers.https://github.com/xiph/opus/blob/16160ac68c8296f695c49c9847221608b084b5f9/include/opus.h#L36

An application can specify  `#include <opus/opus.h>`,  while only specifying the parent include path, such as `/usr/include` or` /usr/local/include`, knowing that the opus directory is inside.

This actually does work as intended for the opus library. 

Notice opus.h has these includes:

```
#include "opus_types.h"
#include "opus_defines.h"
```

As do the following:
```
ops_multistream.h:#include "opus.h"
opus_projection.h:#include "opus_multistream.h"
```

If opus.h switched to `include <opus_types.h>` statements, then yes, it would also require `-I/usr/include/opus` just like opusfile does right now.

**Comment by krcroft** [comment]
Also see the same thing in vorbisfile.h - it #include "codec.h", which sits along side it in the _vorbis_ include directory.  Notice how it doesn't #include <codec.h>, because that would require you expliciting -I/path/to/include/vorbis

https://github.com/xiph/vorbis/blob/master/include/vorbis/vorbisfile.h

**Comment by SephiRok** [comment]
+1

**Comment by rubyFeedback** [comment]
I ran into a similar issue - SDL2-mixer complains about being unable to find
opus multistream.h. I have libopus and opusfile installed though.

Something seems odd here.

    /usr/include/opus/opusfile.h:110:11: fatal error: opus_multistream.h: No such file or directory
      110 | # include <opus_multistream.h>

The confusing part (to me) is that opusfile.h complains about opus_multistream.h but it
seems to be the one that requires it; how else would SDL2-mixer get confused about
asking it? Could be a bug in SDL2-mixer, but either way the situation is quite confusing,
in my opinion. Perhaps the path fix by ienapliss has solved this, I am not sure.

**Comment by Chrd26** [comment]
> I ran into a similar issue - SDL2-mixer complains about being unable to find opus multistream.h. I have libopus and opusfile installed though.
> 
> Something seems odd here.
> 
> ```
> /usr/include/opus/opusfile.h:110:11: fatal error: opus_multistream.h: No such file or directory
>   110 | # include <opus_multistream.h>
> ```
> 
> The confusing part (to me) is that opusfile.h complains about opus_multistream.h but it seems to be the one that requires it; how else would SDL2-mixer get confused about asking it? Could be a bug in SDL2-mixer, but either way the situation is quite confusing, in my opinion. Perhaps the path fix by ienapliss has solved this, I am not sure.

I just stumbled upon the same issue. I am on MacOS and it started happening after updating the XCode CLI tools. Rebuilding the SDL mixer library fixed it for me.

**Comment by barracuda156** [comment]
It should be `"opus_multistream.h"`, not `<opus_multistream.h>`.
