### ISSUE TITLE
Is there any document about how to use opusfile?

### ISSUE THREAD

**Issue by willson-chen** [xiph/opusfile#14]
Document just like quick start guide, not API reference

**Comment by maestroIgor** [comment]
Best I've managed to find:
https://bluishcoder.co.nz/2009/06/24/reading-ogg-files-using-libogg.html

**Comment by maestroIgor** [comment]
Example [https://github.com/xiph/opusfile/blob/master/examples/opusfile_example.c](url) is a good "quick" start guide if you ignore branch with treating the input argument as a URL.

**Comment by willson-chen** [comment]
@maestroIgor . Thanks for your reply. :)
