### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by hhyyrylainen** [xiph/opusfile#15]
Opus has support for configuring with cmake. It would be nice for opusfile to also support cmake.

**Comment by simoncent** [comment]
Ogg also has CMake support. It makes it very easy to integrate Ogg/Opus support into a CMake build, until you get to Opusfile :(

There appears to be a few existing solutions about which you could adopt and build on, for example:
https://github.com/eppixx/opusfile-cmake

**Comment by rillian** [comment]
Fixed in cf218fb54929a1f54e30e2cb208a22d08b08c889. Thanks @h3ndrk!
