### ISSUE TITLE
A potential bug of NPD

### ISSUE THREAD

**Issue by ash1852** [xiph/opusfile#36]
Hi, I found a potential null pointer dereference bug in the project source code of opusfile, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug, the red arrows represent the control flow,the file path can be seen in the blue framed section.
![image](https://user-images.githubusercontent.com/87304478/188381342-12a4a003-a097-4c8d-9025-dc2194a80751.png)
Although the code shown is for version 0.9  but is still exist in current version
https://github.com/xiph/opusfile/blob/cf218fb54929a1f54e30e2cb208a22d08b08c889/src/opusfile.c#L1527-L1532

would you can help to check if this bug is true?thank you for your effort and patience!

**Comment by rillian** [comment]
A lot of our code assumes `malloc` is infallible, just like we don't validate any of the pointer arguments in this function. But it looks like opusfile does check occasionally, so checking and returning `OP_EFAULT` would be reasonable here.

**Comment by ash1852** [comment]
ok.thank you for your effort.

**Comment by rillian** [comment]
Fixed in 0a4cd796df5b030cb866f3f4a5e41a4b92caddf5. Thanks for the report!

**Comment by nanonyme** [comment]
@rillian  would it be possible to actually make a release with this fix? There is a CVE reported against this and everyone is now applying the patch downstream while waiting for opusfile release.
